### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by shinsonwu** [JingChunzhen/churn_analysis#1]
I'm interested in you anaylsis.It's funny.
Is it convnient to provide the dateset, just used for studying the application of ML in  game anylsis .
Tks.

**Comment by JingChunzhen** [comment]
The format of data is 
CREATE TABLE maidian (ObjectID INTEGER PRIMARY KEY, riqi INTEGER, user_id INTEGER, action TEXT, zhanli INTEGER, dengji INTEGER, jinbi INTEGER, zuanshi INTEGER, heizuan INTEGER, tili INTEGER, ip TEXT, vip TEXT, xitong TEXT, qudao INTEGER, num_days_played INTEGER, current_day INTEGER, relative_timestamp REAL);
current_day Indicates how many days the player played in range num_days_played.
But Sorry, I can not provide you data due to a confidentiality agreement.
And Thank you for your attention to this project.
